### PR TITLE
Update Meetup Group Name & Link #117

### PR DESCRIPTION
**Pull request by monzuralam**

### CODE REVIEW

**Review by Crixu — APPROVED** [review]
looks good. Thanks for updating the links

**Review by pfefferle — CHANGES_REQUESTED** [review]
the actual links seems to be fine! why have you changed them to a completely other event @monzuralam ?

**Comment by pfefferle** [comment]
Ah, I see: https://github.com/WordPress/hosting-handbook/issues/117

Sorry about that 🙄

**Review by pfefferle — APPROVED** [review]
LGTM!

**Pull request merged**
