### PR TITLE
Troubleshooting Security breaches document

### PR DESCRIPTION
**Pull request by pharar**
Some advises of troubleshooting actions for hosting providers in the case of a Security scenario.
Any addition is more than welcome.

### CODE REVIEW

**Comment by getsource** [comment]
Initial thoughts ([partially from Slack](https://wordpress.slack.com/archives/C3D6T7F8Q/p1614765009114700), from today's triage):
- I like the idea of the content, thank you!
- I think it’d be good to avoid recommending any specific commercial services.
- Agreed with some others in the channel that security team review would be great.

**Comment by Crixu** [comment]
Reached out to Ian Dunn from the security team to also get their review on this.

**Comment by iandunn** [comment]
Hi 👋🏻 

It seems like there's a lot of similarity between this and the [My Site Was Hacked FAQ](https://wordpress.org/support/article/faq-my-site-was-hacked/). Does this page have a different goal than that one?

If not, I'd recommend linking to that instead of creating a new one. You could then collaborate w/ Support to make improvements to that article.

Or maybe link to that for the "reactive", and have this focus on the "proactive" steps? Or link to that for user-focused tips, and make this focused on tips for hosting providers?

**Comment by pharar** [comment]
> Hi 👋🏻
> 
> It seems like there's a lot of similarity between this and the [My Site Was Hacked FAQ](https://wordpress.org/support/article/faq-my-site-was-hacked/). Does this page have a different goal than that one?
> 
> If not, I'd recommend linking to that instead of creating a new one. You could then collaborate w/ Support to make improvements to that article.
> 
> Or maybe link to that for the "reactive", and have this focus on the "proactive" steps? Or link to that for user-focused tips, and make this focused on tips for hosting providers?

You are right. This is an old documentation proposal page, so I'm opening an issue to work in that article. Thanks!

**Pull request closed without merging**
