### PR TITLE
New security page proposal

### PR DESCRIPTION
**Pull request by javiercasares**
A lot of changes to discuss...

### CODE REVIEW

**Comment by getsource** [comment]
Thanks for the updates! A lot of this is much easier to read.

I'm noticing that much of this page got removed, without sections getting added back in for some of the content.

Thinking we should discuss this, and run the proposed changes by the security team for approval before making it live, unless that has already happened.

**Comment by javiercasares** [comment]
Yes, also there are some issues and PR about adding some things to the security section... #30 and #33

And yes, we should add some of the Security people to focus on the "hosting" part (and what we should explain of security in the WordPress part). We talked about if we should explain things about security (Core, plugins, etc) or relay that to others.

**Comment by getsource** [comment]
I'm concerned that this might end up live before we have a chance to discuss a bit more, and have a security review. Both to make sure we don't remove parts that are useful/important to users, and also to be aligned, and not misrepresent the security team.

As some background, the version that is currently on the handbook (that this would replace) was reviewed/approved by the security team.

**Comment by getsource** [comment]
I suppose I should be more direct -- apologies! 

I'm wondering if we should revert this for a bit more discussion and review, since otherwise we won't be able to control when it gets sync'd to the handbook. Short of asking meta to wait, of course.

**Comment by javiercasares** [comment]
Yeah, of course... this is the first version... as we talked yesterday, we should not automate anything until we have a full version of the new Handbook, so we can retrieve the older version or work in that adding or removing things. Whatever works best for you. Probably if I revert this commit I will break something, so, if anyone can do it or tell me how to do it, will be better :D

**Comment by getsource** [comment]
Thanks, and sorry about that. Working on finding someone from the security team to take a look so that this doesn't stall out.

**Comment by aaroncampbell** [comment]
Hey all, this **definitely** needs a review by the security team before it can go live, and should be reverted until it can be. It looks like a really significant rewrite, can I ask what the specific purpose was here?
- What are we trying to add that wasn't there before?
- What are we removing?
- What things are being changed?

That would help me try to match things up and actually review what's happening here.

**Comment by javiercasares** [comment]
I split the changes into some issues, so we can discuss the changes in each one.

**Pull request merged**
