### PR TITLE
Changelog added

### PR DESCRIPTION
**Pull request by javiercasares**
- Added, at the end of each page, a new Changelog version with some dates and changes.
- Added the infobox at the end of each pages so all pages have the same information.

### CODE REVIEW

**Review by Crixu — APPROVED** [review]
Great work :)

**Comment by getsource** [comment]
I like the changes.

Am wondering, should this be two separate changes -- one for the infobox, and one for the changelog?

**Comment by javiercasares** [comment]
The infobox was not there from the last big update... so, this was a "up-to-date" on the all footers, also adding the Changelog.

I can separate that, but I did not do that because it didn't change the main content...

**Comment by getsource** [comment]
It'd be my personal preference to split the two, so it's clear when the changelog was added, and when the infobox was added. *Might* also help for reference later, if either or both end up with automation.

As is, I'm a little confused about the sequence of events, so figured I'd say something, but as it gives the same end result, however it works out is fine. :)

**Pull request merged**
