### PR TITLE
Fixing infoboxes

### PR DESCRIPTION
**Pull request by javiercasares**
Fixing the infoboxes without backslash

### CODE REVIEW

**Review by Crixu — APPROVED** [review]
Easy to review PR. Thank you looks great

**Comment by amykamala** [comment]
Looks good! I recommend changing the text "check the [Github Handbook repo](https://github.com/WordPress/hosting-handbook/)" to "check the [Github Handbook repo](https://github.com/WordPress/hosting-handbook/) for more info"

**Comment by Crixu** [comment]
I would vote to keep this PR for the purpose of fixing the backslash. Once merged I'll create another PR with the "for more info" addition :)

**Review by pfefferle — APPROVED** [review]
LGTM!

**Pull request merged**
